"""Top-level package for Satel Integra."""

from .exceptions import (
    SatelCommandRejectedError,
    SatelConnectFailedError,
    SatelConnectionError,
    SatelConnectionInitializationError,
    SatelConnectionSetupError,
    SatelConnectionStoppedError,
    SatelIntegraError,
    SatelMonitoringStartError,
    SatelPanelBusyError,
    SatelUnexpectedResponseError,
)
from .models import (
    SatelCommandResult,
    SatelCommunicationModuleInfo,
    SatelDeviceInfo,
    SatelDeviceType,
    SatelFirmwareVersion,
    SatelOutputInfo,
    SatelPanelInfo,
    SatelPanelModel,
    SatelPartitionInfo,
    SatelResultCode,
    SatelRtcAndStatus,
    SatelZoneInfo,
)
from .satel_integra import AlarmState, AsyncSatel

__all__ = [
    "AlarmState",
    "AsyncSatel",
    "SatelCommandRejectedError",
    "SatelCommandResult",
    "SatelCommunicationModuleInfo",
    "SatelConnectFailedError",
    "SatelConnectionError",
    "SatelConnectionInitializationError",
    "SatelConnectionSetupError",
    "SatelConnectionStoppedError",
    "SatelDeviceInfo",
    "SatelDeviceType",
    "SatelFirmwareVersion",
    "SatelIntegraError",
    "SatelMonitoringStartError",
    "SatelOutputInfo",
    "SatelPanelBusyError",
    "SatelPanelInfo",
    "SatelPanelModel",
    "SatelPartitionInfo",
    "SatelResultCode",
    "SatelRtcAndStatus",
    "SatelUnexpectedResponseError",
    "SatelZoneInfo",
]
